# Generated by Django 3.1.7 on 2022-03-05 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0002_auto_20220305_1342'),
        ('developer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ratingAlgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings', models.IntegerField(default=0)),
                ('review', models.CharField(max_length=200)),
                ('algs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authority.algodetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
