# Generated by Django 3.1.7 on 2022-03-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0002_ratingalgs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratingalgs',
            name='user',
        ),
        migrations.AddField(
            model_name='ratingalgs',
            name='Rateduser',
            field=models.IntegerField(default=0),
        ),
    ]
