# Generated by Django 3.1.7 on 2022-03-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algodetails',
            name='userId',
            field=models.IntegerField(default=0),
        ),
    ]
